# Alibaba
DOMAIN-KEYWORD,alibaba-inc
DOMAIN-KEYWORD,alibaba
DOMAIN-KEYWORD,alipay-inc
DOMAIN-KEYWORD,aliyuncs
DOMAIN-KEYWORD,alipay
DOMAIN-KEYWORD,taobao
DOMAIN-KEYWORD,alicdn
DOMAIN-KEYWORD,aliyun
DOMAIN-KEYWORD,9game
DOMAIN-KEYWORD,ucweb

# Battle.net
DOMAIN-SUFFIX,blizzard.com
DOMAIN-SUFFIX,battle.net

# P2P
PROCESS-NAME,*Folx*
PROCESS-NAME,*Thunder*
PROCESS-NAME,*DownloadService*
PROCESS-NAME,*Soda*
PROCESS-NAME,*p4pclient*
PROCESS-NAME,aria2c
PROCESS-NAME,fdm
PROCESS-NAME,Folx
PROCESS-NAME,NetTransport
PROCESS-NAME,Transmission
PROCESS-NAME,uTorrent
PROCESS-NAME,WebTorrent
PROCESS-NAME,WebTorrent Helper
DOMAIN-KEYWORD,tracker

# Booking
DOMAIN-SUFFIX,booking.com
DOMAIN-SUFFIX,booking.cn

# Misc
PROCESS-NAME,百度网盘
PROCESS-NAME,*Clash*
PROCESS-NAME,*clash*
PROCESS-NAME,v2ray
PROCESS-NAME,ss-local
PROCESS-NAME,ssr-local
# iStat Menu IP Test
DOMAIN,ip.bjango.com
DOMAIN-SUFFIX,biquge.com.tw
DOMAIN-SUFFIX,maoyun.tv
DOMAIN-SUFFIX,moke.com
DOMAIN-SUFFIX,test-ipv6.com
DOMAIN-SUFFIX,zimuzu.tv
DOMAIN-SUFFIX,zmzapi.com
DOMAIN-SUFFIX,zmzapi.net
DOMAIN-SUFFIX,zmzfile.com

# China Apps
USER-AGENT,MApi*
USER-AGENT,MicroMessenger*
USER-AGENT,WeChat*
DOMAIN-SUFFIX,cn
DOMAIN-KEYWORD,-cn
DOMAIN-KEYWORD,alicdn
DOMAIN-SUFFIX,126.com
DOMAIN-SUFFIX,126.net
DOMAIN-SUFFIX,127.net
DOMAIN-SUFFIX,163.com
DOMAIN-SUFFIX,360buyimg.com
DOMAIN-SUFFIX,36kr.com
DOMAIN-SUFFIX,acfun.tv
DOMAIN-SUFFIX,air-matters.com
DOMAIN-SUFFIX,aixifan.com
DOMAIN-SUFFIX,weibo.com
DOMAIN-SUFFIX,alipayobjects.com
DOMAIN-SUFFIX,amap.com
DOMAIN-SUFFIX,autonavi.com
DOMAIN-SUFFIX,baidu.com
DOMAIN-SUFFIX,baidupcs.com
DOMAIN-SUFFIX,bdimg.com
DOMAIN-SUFFIX,bdstatic.com
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,caiyunapp.com
DOMAIN-SUFFIX,clouddn.com
DOMAIN-SUFFIX,cnbeta.com
DOMAIN-SUFFIX,cnbetacdn.com
DOMAIN-SUFFIX,cootekservice.com
DOMAIN-SUFFIX,csdn.net
DOMAIN-SUFFIX,ctrip.com
DOMAIN-SUFFIX,dgtle.com
DOMAIN-SUFFIX,dianping.com
DOMAIN-SUFFIX,douban.com
DOMAIN-SUFFIX,doubanio.com
DOMAIN-SUFFIX,duokan.com
DOMAIN-SUFFIX,easou.com
DOMAIN-SUFFIX,ele.me
DOMAIN-SUFFIX,fast.com
DOMAIN-SUFFIX,feng.com
DOMAIN-SUFFIX,fir.im
DOMAIN-SUFFIX,frdic.com
DOMAIN-SUFFIX,g-cores.com
DOMAIN-SUFFIX,godic.net
DOMAIN-SUFFIX,gtimg.com
DOMAIN-SUFFIX,hongxiu.com
DOMAIN-SUFFIX,hxcdn.net
DOMAIN-SUFFIX,iciba.com
DOMAIN-SUFFIX,ifeng.com
DOMAIN-SUFFIX,ifengimg.com
DOMAIN-SUFFIX,images-amazon.com
DOMAIN-SUFFIX,ipip.net
DOMAIN-SUFFIX,iqiyi.com
DOMAIN-SUFFIX,jd.com
DOMAIN-SUFFIX,jianshu.com
DOMAIN-SUFFIX,knewone.com
DOMAIN-SUFFIX,le.com
DOMAIN-SUFFIX,lecloud.com
DOMAIN-SUFFIX,lemicp.com
DOMAIN-SUFFIX,luoo.net
DOMAIN-SUFFIX,meituan.com
DOMAIN-SUFFIX,meituan.net
DOMAIN-SUFFIX,mi.com
DOMAIN-SUFFIX,miaopai.com
DOMAIN-SUFFIX,miui.com
DOMAIN-SUFFIX,miwifi.com
DOMAIN-SUFFIX,mob.com
DOMAIN-SUFFIX,netease.com
DOMAIN-SUFFIX,oschina.net
DOMAIN-SUFFIX,ppsimg.com
DOMAIN-SUFFIX,pstatp.com
DOMAIN-SUFFIX,qcloud.com
DOMAIN-SUFFIX,qdaily.com
DOMAIN-SUFFIX,qdmm.com
DOMAIN-SUFFIX,qhimg.com
DOMAIN-SUFFIX,qidian.com
DOMAIN-SUFFIX,qihucdn.com
DOMAIN-SUFFIX,qiniu.com
DOMAIN-SUFFIX,qiniucdn.com
DOMAIN-SUFFIX,qiyipic.com
DOMAIN-SUFFIX,qq.com
DOMAIN-SUFFIX,qqurl.com
DOMAIN-SUFFIX,rarbg.is
DOMAIN-SUFFIX,rr.tv
DOMAIN-SUFFIX,ruguoapp.com
DOMAIN-SUFFIX,segmentfault.com
DOMAIN-SUFFIX,sinaapp.com
DOMAIN-SUFFIX,sogou.com
DOMAIN-SUFFIX,sogoucdn.com
DOMAIN-SUFFIX,sohu.com
DOMAIN-SUFFIX,soku.com
DOMAIN-SUFFIX,speedtest.net
DOMAIN-SUFFIX,sspai.com
DOMAIN-SUFFIX,suning.com
DOMAIN-SUFFIX,tenpay.com
DOMAIN-SUFFIX,tmall.com
DOMAIN-SUFFIX,tudou.com
DOMAIN-SUFFIX,umetrip.com
DOMAIN-SUFFIX,upaiyun.com
DOMAIN,update.microsoft.com
DOMAIN-SUFFIX,upyun.com
DOMAIN-SUFFIX,veryzhun.com
DOMAIN-SUFFIX,weibo.com
DOMAIN-SUFFIX,xiami.com
DOMAIN-SUFFIX,xiami.net
DOMAIN-SUFFIX,xiaomicp.com
DOMAIN-SUFFIX,ximalaya.com
DOMAIN-SUFFIX,xmcdn.com
DOMAIN-SUFFIX,xunlei.com
DOMAIN-SUFFIX,yhd.com
DOMAIN-SUFFIX,yihaodianimg.com
DOMAIN-SUFFIX,yinxiang.com
DOMAIN-SUFFIX,ykimg.com
DOMAIN-SUFFIX,youdao.com
DOMAIN-SUFFIX,youku.com
DOMAIN-SUFFIX,zealer.com
DOMAIN-SUFFIX,zhihu.com
DOMAIN-SUFFIX,zhimg.com
DOMAIN-SUFFIX,chinacloudapi.cn
DOMAIN-SUFFIX,mymm.com
DOMAIN-SUFFIX,akadns.net
